%MACRO MEDIAPONDERATA(
		DATA   = , 
		VAR = ,
		PESO   = , 
		GRUPPO = );


data &data.;
set  &data.;
drop SOMMA_PESI_&var. &VAR._AVG;
run;

* CALCOLO DEI PESI TOTALI;
PROC SQL;
CREATE TABLE &DATA. AS
SELECT 	*,	
			SUM(&PESO.) AS SOMMA_PESI_&var.,
			(&VAR. * &PESO. )/ CALCULATED SOMMA_PESI_&var. AS TO_BE_SUMMED
FROM &DATA.

GROUP BY &GRUPPO.
HAVING CALCULATED SOMMA_PESI_&var. >0
ORDER BY &GRUPPO.
;
QUIT;

PROC SQL;
CREATE TABLE &DATA. AS
SELECT  *, SUM(TO_BE_SUMMED) AS &VAR._AVG
FROM &DATA.
GROUP BY &GRUPPO.
ORDER BY &GRUPPO.
;
QUIT;

PROC SQL;
ALTER TABLE &DATA.
DROP  TO_BE_SUMMED
;
QUIT;

PROC SQL;
CREATE TABLE &DATA. AS
SELECT DISTINCT * 
FROM &DATA.
ORDER BY &GRUPPO.
;
QUIT;


%MEND;


%PUT PARAMETRI: MEDIAPONDERATA(
		DATA   = , 
		VAR = ,
		PESO   = , 
		GRUPPO = );
