
* AGGIUNGE VARIABILE NUMERICA CON FORMATO UGUALE ALLA VARIABILE RANGE DI PARTENZA;



%MACRO VAR_RANGE(DATA = , VAR = );


PROC SQL;
CREATE TABLE &VAR._CAT AS 
SELECT DISTINCT &VAR.,&VAR. AS LABEL, INPUT(SCAN(TRIM(&VAR.),1) , BEST12.)  AS INF , 
						INPUT(SCAN(TRIM(&VAR.),-1), BEST12.)  AS SUP ,
						(CALCULATED INF + CALCULATED SUP) / 2 AS &VAR._CENTRAL
FROM &DATA.
ORDER BY CALCULATED INF;
QUIT;

DATA &VAR._CAT;
LENGTH FMTNAME $ 35;
SET &VAR._CAT ;
START = _N_;
FMTNAME = "&VAR._FMT";
RUN;

PROC SQL;
INSERT INTO &VAR._CAT
SET FMTNAME = "&VAR._FMT",
	LABEL = "NULL",
	START = 0
	;
QUIT;

PROC FORMAT CNTLIN=&VAR._CAT ;
RUN;

PROC SQL;
CREATE TABLE &DATA. AS
SELECT D.* , F.START AS &VAR._CAT FORMAT = &VAR._FMT.,
			&VAR._CENTRAL
FROM &DATA. D
	LEFT JOIN &VAR._CAT F
	ON D.&VAR. = F.&VAR.
;
QUIT;

proc datasets noprint;
delete &VAR._CAT;
run;

%MEND VAR_RANGE;

%PUT PARAMETRI VAR_RANGE(DATA = , VAR = );
